services:
  selenoid:
    image: aerokube/selenoid:1.11.3
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./browsers.json:/etc/selenoid/browsers.json"
    command:
      - "-conf"
      - "/etc/selenoid/browsers.json"
      - "-video-output-dir"
      - "/opt/selenoid/video"
      - "-container-network"
      - "ui-banking-project_default"

#  selenoid-ui:
#    image: aerokube/selenoid-ui:latest
#    ports:
#      - "8084:8080"
#    command:
#      - "--selenoid-uri"
#      - "http://selenoid:4444"

  test-runner:
    build: .
    depends_on:
    - selenoid
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
    volumes:
      - .:/app
      - maven-cache:/root/.m2
      - ./allure-results:/app/allure-results
    command: mvn clean test

volumes:
  maven-cache: